### ISSUE TITLE
Prepare for 1.3 release

### ISSUE THREAD

**Issue by dicato** [macropin/django-registration#131]
**This is a work in progress...**

## todo

* [x] update `CHANGELOG`
* [x] update version number to `1.3`
* [x] merge #94

**Comment by areski** [comment]
I would love to use it with Django1.9, we need a release :) let me know if you need help

**Comment by dicato** [comment]
@areski I'd love help. Here's a couple tasks that I think need to be done before a new release:

* [ ] review and test #94
* [ ] review and test #113 
* [ ] review and test #115 

Those three have passing tests and have not dropped test coverage. The remaining open pull requests either are work in progress or have dropped test coverage a bit.

I'd also love help with updating the `CHANGELOG` as it's lacks any details about changes since 1.2.

**Comment by areski** [comment]
I cannot really test #94 but I tested #113 (added comment) and #115 (I added a extra commit), you can see https://github.com/macropin/django-registration/pull/137.

I think #113 & #115 can be merged without fear.

Cheers!

**Comment by dicato** [comment]
Hopefully @mick-t can rebase and comment about #94 and confirm that it still works.

This is getting closer :smile:

**Comment by areski** [comment]
I'm actually curious if #94 is a popular issue? maybe we should consider a release without it, well maybe let give it a couple of day and see

**Comment by dicato** [comment]
@areski I agree with your sentiment. I suspect south is "mostly unused" with this package. I'm slightly concerned that broken migrations landed in master and might bite someone however.

**Comment by mcrowson** [comment]
In the docs it says that Django 1.7 or newer is required. It looks like #94 deals with <1.7. As this release will fix 1.9 for us, I would love a release sooner than later without #94.

**Comment by macropin** [comment]
I think there are some missed references in the rst docs. @dicato are you able to fix these up and add to #142?

**Comment by dicato** [comment]
@macropin I pushed another commit that fixed the obvious references to `1.2`. If there is anything else please let me know.

**Comment by macropin** [comment]
@dicato `docs/upgrade.rst` needs updating too.

**Comment by dicato** [comment]
@macropin I pushed another commit. I am unsure if there are any backwards incompatibilities since the 1.2 release.

**Comment by macropin** [comment]
@dicato It now requires Django > 1.7

**Comment by macropin** [comment]
v1.3 release has been made to PyPi. Thanks to all those that helped.

**Comment by dicato** [comment]
:+1: thanks!

**Comment by areski** [comment]
Indeed a big thanks for that :)

**Comment by mick-t** [comment]
I can still rebase if you like? Sorry for the late reply, I was out of internet range for a few weeks. :)
